// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/[name].tsx';
import * as $1 from './routes/api/joke.ts';
import * as $2 from './routes/api/prediction.ts';
import * as $3 from './routes/index.tsx';
import * as $4 from './routes/prediciton.tsx';
import * as $5 from './routes/reports.tsx';
import * as $$0 from './islands/Counter.tsx';
import * as $$1 from './islands/Dashboard.tsx';
import * as $$2 from './islands/StudentReport.tsx';

const manifest = {
	routes: {
		'./routes/[name].tsx': $0,
		'./routes/api/joke.ts': $1,
		'./routes/api/prediction.ts': $2,
		'./routes/index.tsx': $3,
		'./routes/prediciton.tsx': $4,
		'./routes/reports.tsx': $5,
	},
	islands: {
		'./islands/Counter.tsx': $$0,
		'./islands/Dashboard.tsx': $$1,
		'./islands/StudentReport.tsx': $$2,
	},
	baseUrl: import.meta.url,
};

export default manifest;
